env:
  browser: true
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - plugin:es5/no-es2015
  - airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - es5
rules:
  no-var: 0
  prefer-template: 0
  eslintvars-on-top: 0
  vars-on-top: 0
  no-underscore-dangle: 0
  no-param-reassign: 0
  prefer-destructuring: 1
  no-restricted-syntax: 1
  camelcase: 1
eslint:
  autoFixOnSave: 0